server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: ${SERVER_MAX_FILE_SIZE}
      max-request-size: ${SERVER_MAX_FILE_SIZE}

  security:
    oauth2:
      client:
        registration:
          moj-identity:
            client-id: ${AUTH_CLIENT_ID}
            client-secret: ${AUTH_CLIENT_SECRET}
            scope: ${AUTH_SCOPE}
            authorization-grant-type: client_credentials
        provider:
          moj-identity:
            issuer-uri: https://login.microsoftonline.com/${AUTH_TENANT_ID}/v2.0

sds-api:
  url: ${SDS_API_URL}

cwa-api:
  url: ${CWA_API_URL}
  timeout: ${CWA_API_TIMEOUT}

upload-max-file-size: ${UPLOAD_MAX_FILE_SIZE}

rest-client:
  connect-timeout: ${REST_CLIENT_CONNECT_TIMEOUT}
  read-timeout: ${REST_CLIENT_READ_TIMEOUT}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
