server:
  port: 8082
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

azure:
  entra-id:
    client-id: ${SSO_CLIENT_ID}
    client-secret: ${SSO_CLIENT_SECRET}
    cloud-instance: ${SSO_CLOUD_INSTANCE}
    scope: ${SSO_SCOPE}
    tenant-id: ${SSO_TENANT_ID}

sds-api:
  url: ${SDS_API_URL}

