apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-cwa-bulk-upload-deployment
  labels:
    app: laa-cwa-bulk-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laa-cwa-bulk-upload # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: laa-cwa-bulk-upload # this should match the selector in service.yml
    spec:
      containers:
        - name: laa-cwa-bulk-upload
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8082
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: SDS_API_URL
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: SDS_API_URL
            - name: SSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: SSO_CLIENT_ID
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: SSO_CLIENT_SECRET
            - name: SSO_CLOUD_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: SSO_CLIENT_SECRET
            - name: SSO_SCOPE
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: SSO_SCOPE
            - name: SSO_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: SSO_TENANT_ID
