name: PR build and test
on:
  workflow_dispatch:
#  pull_request:
#    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Run tests
        uses: './.github/build-and-test'